// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfivycvcxwxkswiavoyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmaXZ5Y3ZjeHd4a3N3aWF2b3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzI0NDIsImV4cCI6MjA1MTg0ODQ0Mn0.0QNWtrXeKNzDgQzCcW70xJgy5xsvg98mxTfctiGaPKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);